### ISSUE TITLE
Doesn't work on rustc

### ISSUE THREAD

**Issue by bjorn3** [tarasglek/bpftrace_pagefaults#1]
The rustc rust compiler mmaps a lot of files to load metadata as part of the compilation process. This tool reports an unknown filename for all files.

## Reproduction

1. Install rust from https://www.rust-lang.org/learn/get-started
2. Run `sudo bpftrace mmap_pagefault_snoop.bt | grep rustc | ./process.py`
3. Run `echo 'fn main() {}' | rustc -` in another terminal.
4. Getting a lot of output like
    ```
    -1 1027720
    -1 70688
    -1 8359856
    -1 84112
    94100185841352 not found
    94100185869016 not found
    -1 59632
    -1 81304
    -1 1151872
    94100185863752 not found
    -1 1024000
    -1 896
    -1 8366040
    -1 1029288
    -1 94528
    -1 53312
    ```
    from `process.py`.

## Investigation

When uncommenting the open printf I noticed that a lot of paths are truncated due to being longer than 64 characters. Using setting the `BPFTRACE_STRLEN=200` env var prevents truncation. However it doesn't help with `process.py`. I also noticed that the mmap calls are entirely absent from the bpftrace output despite strace seeing them.

**Comment by tarasglek** [comment]
Sorry, didn't notice your issue sooner. Turns out hooking into mmap and pagefaults is very fragile. It had better success with hooking into tracing ext4 mmap handling via https://github.com/tarasglek/bpftrace_pagefaults/blob/main/artifacts/ext4.bt

**Comment by tarasglek** [comment]
Here is a sample log from running:
`bpftrace artifacts/ext4.bt  > /tmp/log.txt`

and 

`sysctl -w vm.drop_caches=3; rustc`

[log.txt](https://github.com/tarasglek/bpftrace_pagefaults/files/8246432/log.txt)

**Comment by bjorn3** [comment]
Thanks for the reply! Unfortunately that bpftrace script doesn't work with my kernel version:

```
artifacts/ext4.bt:12-14: ERROR: kfunc/kretfunc not available for your kernel version.
artifacts/ext4.bt:16:13-23: ERROR: Can't find a field
    $page = args->page;
            ~~~~~~~~~~
artifacts/ext4.bt:17:13-24: ERROR: Can't find a field
    $node = args->inode;
            ~~~~~~~~~~~
artifacts/ext4.bt:18:12-21: ERROR: Can't find a field
    $rac = args->rac;
           ~~~~~~~~~
```

I may try it again in the future once I get a newer kernel.
